### ISSUE TITLE
fix(gamesmenu): represent SG1000 ROM definitions correctly

### ISSUE THREAD

**Issue by FiZiX** [wizzomafizzo/mrext#177]
Thank you for this awesome script! I wanted to report this exception that occurred during scanning of my SG1000 folder:

`Traceback (most recent call last):
  File "/media/fat/Scripts/./gamesmenu.sh", line 464, in <module>
    display_generate_mgls(systems)
  File "/media/fat/Scripts/./gamesmenu.sh", line 317, in display_generate_mgls
    for system, path, parent, filename, match in get_system_files(
  File "/media/fat/Scripts/./gamesmenu.sh", line 214, in get_system_files
    match = match_system_file(system, zip_path)
  File "/media/fat/Scripts/./gamesmenu.sh", line 166, in match_system_file
    if ext.lower() in type[0]:
TypeError: 'set' object is not subscriptable
`

I was able to get around it by disabling Coleco in my games menu. SG1000 was already disabled.

**Comment by wizzomafizzo** [comment]
Implemented in commit 9f3a97d. The SG1000 entry now stores its ROM definition inside the outer tuple expected by GamesMenu and Favorites scanners.
