### ISSUE TITLE
Playlog - error updating with update_all script

### ISSUE THREAD

**Issue by marceloMedeiros** [wizzomafizzo/mrext#9]
When i run update all i get the error (and a leftover file on the scripts folder named playlog.sh._downloader_in_progress):

Scripts/playlog.sh
**Traceback (most recent call last):
  File "/tmp/tmp7qqs6oho/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/tmp7qqs6oho/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/tmp7qqs6oho/downloader/full_run_service.py", line 58, in full_run
    result = self._full_run_impl()
  File "/tmp/tmp7qqs6oho/downloader/full_run_service.py", line 117, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/tmp7qqs6oho/downloader/online_importer.py", line 95, in download_dbs_contents
    db_importer.process_changed_files(changed_files, needed_zips, filtered_zip_data)
  File "/tmp/tmp7qqs6oho/downloader/online_importer.py", line 588, in process_changed_files
    file_downloader.download_files(self._is_first_run())
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 141, in download_files
    self._errors = self._download_try()
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 172, in _download_try
    self._fetch_whole_queue(low_level)
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 204, in _fetch_whole_queue
    low_level.fetch(files_to_download, self._queued_files)
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 292, in fetch
    remaining_notifications -= self._read_notifications(descriptions, notify_queue, True)
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 318, in _read_notifications
    self._pending_notifications.append(self._download_validator.validate_download(path, descriptions[path]['hash']))
  File "/tmp/tmp7qqs6oho/downloader/file_downloader.py", line 216, in validate_download
    self._target_path_repository.finish_target(file_path)
  File "/tmp/tmp7qqs6oho/downloader/target_path_repository.py", line 82, in finish_target
    self._file_system.copy(target_path, path)
  File "/tmp/tmp7qqs6oho/downloader/file_system.py", line 184, in copy
    return shutil.copyfile(self._path(source), self._path(target))
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
OSError: [Errno 26] Text file busy: '/media/fat/Scripts/playlog.sh'

**Comment by wizzomafizzo** [comment]
Hi mate. If you delete playlog.sh from your Scripts folder and run update again it should be fixed. This is a bug from a while ago. Shouldn't happen again after that and you won't lose any data

**Comment by marceloMedeiros** [comment]
> Hi mate. If you delete playlog.sh from your Scripts folder and run update again it should be fixed. This is a bug from a while ago. Shouldn't happen again after that and you won't lose any data

Thank you, i did what you suggested and its updating fine now :)
